# Generated by Django 3.2.7 on 2021-09-25 06:41

from django.db import migrations, models
import markdownx.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do', markdownx.models.MarkdownxField()),
                ('study', markdownx.models.MarkdownxField()),
                ('review', markdownx.models.MarkdownxField()),
                ('score', model_utils.fields.StatusField(choices=[(0, 'VeryGood'), (1, 'Good'), (2, 'Normal'), (3, 'Bad'), (4, 'WTF')], default=0, max_length=100, no_check_for_status=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
