# Generated by Django 3.2.7 on 2021-09-27 03:09

from django.db import migrations, models
import markdownx.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_daily_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='do',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='daily',
            name='review',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='study',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
