# Generated by Django 3.2.7 on 2021-09-27 03:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_daily_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
