# Generated by Django 3.2.7 on 2021-09-27 05:20

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_daily_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='score',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='verygood', max_length=100, no_check_for_status=True),
        ),
    ]
