# Generated by Django 3.2.7 on 2021-09-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_daily_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
